# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexis Lessard
email: alexis_lessard@outlook.com
description: Alexis Lessard (Sprawls) - Game Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sprawls.github.io" # the base hostname & protocol for your site
twitter_username: Alexis_Lessard
github_username:  Sprawls
linkedin_url:     https://www.linkedin.com/in/alexis-lessard-9374b811a
cv_path :  /public/cv_alexis_lessard.pdf


# Build settings
markdown: kramdown
